name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ESlint on rac-server
        run: cd rac-server
          npm ci
          npx eslint . --ext .js,.jsx
